(defun create-lod-viewer (sObj)
  (interactive "sLod Name: " sObj)
  (setq sObjName sObj)
  (message "Loading LOD: %s" sObjName)
  (setq sObjBuf (concat sObjName ".XOD"))
  (setq sObjPath (concat "~/Projects/emacs/zeidon/src/" sObjBuf))
;  (setq sObjPath (concat "C:\\lplr\\cheetah\\bin\\" sObjName ".XOD"))
  (if (not (bufferp sObjBuf))
      (find-file-noselect sObjPath))    
  (create-lod-view-buffer)
)

(defun create-lod-view-buffer ()
  (setq sLodView (concat "*LOD " sObjName " View*"))
  (if (get-buffer sLodView)
      (kill-buffer sLodView))
  (generate-new-buffer sLodView)
  (switch-to-buffer-other-window sLodView)
  (goto-char (point-min))
  (insert "--------------------------------------------------------------------------\n")
  (insert " Logical Object Definition Viewer for Emacs\n")
  (insert "--------------------------------------------------------------------------\n")
  (insert " Viewing LOD: " sObjName ".LOD\n")
  (insert "--------------------------------------------------------------------------\n\n")
)

(defun get-parent-friendly-name ()
  (if (not (bufferp sObjBuf))
      (set-buffer sObjBuf))

  (goto-char (point-min))
  (search-forward "eENTITY")
  (search-forward "aNAME")
  (skip-chars-forward " ")
  (setq sParentName (extract-word))
)

(defun test-list ()
  (interactive)
  (if (not (bufferp sObjBuf))
      (switch-to-buffer-other-window sObjBuf))
  (setq maxPos (goto-char (point-max)))
  (goto-char 1)
  (setq curPos (point))
  (setq eOBJECT "eOBJECT")
  (setq eENTITY "eENTITY")
  (setq eCHILDENTITY "eCHILDENTITY")
  (setq eATTRIB "eATTRIB")
  (setq aNAME "aNAME")
  (setq eDATARECORD "eDATARECORD")
  
  (while (< curPos maxPos)
   (forward-line 1)
   (beginning-of-line)
   (setq sChk (extract-word))
   (cond ((equal sChk eOBJECT) generate-obj-entity) "Nothing to see")
   (setq curPos (point)))
)


(defun generate-obj-entity ()
  (search-forward aNAME)
  (beginning-of-line)
  (skip-chars-forward " ")
  (setq value (extract-word))
  (if (not (bufferp sLodView))
      (set-buffer sLodView))
  (insert "Object: " value)
  (insert "\n---\n\tTODO: Properties for parent\n---\n")
  (insert "Attributes\n")
)

(defun get-entity-attributes (sEntityName)
  (if (not (bufferp sObjBuf))
      (set-buffer sObjBuf))
  (goto-char 1)
; (while (search-forward "eCHILDENTITY" nil t)
;    (search-forward "aNAME")
;    (skip-chars-forward " ")
;    (setq sEntityName (extract-word))
;    (set-buffer sLodView)
;    (goto-char (point-max))
;    (insert "\n---\n\t"sEntityName "\n---\n")
;    (set-buffer sObjBuf)
;    (while (search-forward "eATTRIB")
;      (search-forward "aNAME")
;      (skip-chars-forward " ")
;      (setq sAttrName (extract-word))
;      (set-buffer sLodView)
;      (goto-char (point-max))
;      (build-full-view-insert sEntityName sAttrName)
;      (set-buffer sObjBuf)))
)     


;; Utilities
(defun extract-word ()
  (let ((start (point)))
    (forward-word)
    (buffer-substring-no-properties start (point)))
)

(defun build-full-view-insert (sEntityName sAttrName)
  (insert (concat "\n\t" sObjName "." sEntityName "." sAttrName))
)

(defun jump-by-start-of-word ()
  (forward-word)
  (backward-word)
)

(defun extract-stop ()
  (jump-by-start-of-word) 
  (extract-word)
)
